### ISSUE TITLE
Uninstalling six-1.4.1 (mac os) 

### ISSUE THREAD

**Issue by yuk** [trueneu/swiss-knife#16]
During execution of the setup command (pip install swk):
`Installing collected packages: six, cryptography, paramiko, scp, chardet, pypsi, swk
  Found existing installation: six 1.4.1
    DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling six-1.4.1`

**Comment by trueneu** [comment]
Guess you're on macosx. There's a problem with upgrading a system-wide six package, you can learn more about it here:
https://github.com/pypa/pip/issues/3165
The most useful comment there how to work around that issue (use your own Python and/or virtualenvs, install packages to a local directory, etc):
https://github.com/pypa/pip/issues/3165#issuecomment-150535535

I'll add this to README.
